nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.12.0.cjs

supportedArchitectures:
  os:
    - current
    - win32
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
